Introduction to Rails
Ustrizhitskiy/TestGuru pull request #1
Opened 2018-03-12 15:58 UTC by Ustrizhitskiy

2018-03-12 18:00 UTC, iBublik requested changes

2018-03-12 18:00 UTC, iBublik commented on config/initializers/version.rb
> +VERSION = '0.1.0'
Каким образом получить доступ к этой константе из приложения? Хотелось бы, чтоб она была обернута в модуль с именем приложения

2018-03-12 18:00 UTC, iBublik commented on README.md
> +- тесты.
Распиши эту сущность чуть подробнее. Из чего состоят тесты?

2018-03-12 18:00 UTC, iBublik commented on config/routes.rb
> +  get 'about', to: 'about_project#about', as: 'about'
Сейчас это целиком статичные странцы. Прогонять их через рельсовое приложение неэффективно. Просто помести html-файлы в папку public, и они будут отдаваться напрямую без участия Rails, что значительно быстрее

2018-03-12 18:19 UTC, Ustrizhitskiy commented on config/initializers/version.rb
> +VERSION = '0.1.0'
У самого был такой вопрос, ждал code rewiew. А если в модуль обернуть, то модуль где подключать (include)? Или он подключается автоматом? Или я что-то не допонимаю

2018-03-12 18:41 UTC, iBublik commented on config/initializers/version.rb
> +VERSION = '0.1.0'
В Ruby можно переоткрывать классы/модули. При этом это не переопределение класса, а его "расширение". Так что если ты запишешь 
```ruby
module MyAppName
  VERSION = '0.1.0'
end
```
Это как раз создаст константу внутри твоего приложения

2018-03-13 18:16 UTC, psylone approved these changes

2018-03-13 18:16 UTC, psylone commented on README.md
> +  - ответы.
Понадобится также хранить факт прохождения теста пользователем.

2018-03-13 18:16 UTC, psylone commented on public/about/author/author.html
> +  <a href="https://github.com/Ustrizhitskiy">Ссылка на профиль GitHub</a>
Ссылка на внешний ресурс должна открываться в новой вкладке.

2018-03-15 05:21 UTC, merged