3.add models
Ustrizhitskiy/TestGuru pull request #2
Opened 2018-03-16 15:56 UTC by Ustrizhitskiy

2018-03-16 19:19 UTC, iBublik requested changes

2018-03-16 19:19 UTC, iBublik commented on db/migrate/20180316151935_create_tests.rb
> +      t.string :title, :null => false
Хэшрокет - устаревшая форма записи хешей, если ключами являются символы. Используй актуальную форму - `t.string :title, null: false`

2018-03-16 19:19 UTC, iBublik commented on db/migrate/20180316152901_create_answers.rb
> +      t.boolean :correct, :default => false
Для логических полей рекомендую всегда задавать опцию `null: false`. Тогда в БД будет строга 2 значения (true/false), а не 3 (true/false/null), что сильно упрощает выборки

2018-03-17 13:40 UTC, psylone approved these changes

2018-03-17 13:40 UTC, psylone commented on db/migrate/20180317071954_add_references_to_answers.rb
> +    add_reference :answers, :question, foreign_key: true
Миграции с `add_reference` стоило объединить в одну.

2018-03-17 13:57 UTC, Ustrizhitskiy commented on db/migrate/20180317071954_add_references_to_answers.rb
> +    add_reference :answers, :question, foreign_key: true
Да, я и сам заметил, что они одинаковые. Но никак не соображу, как можно одной командой было сделать. Подскажи, пожалуйста. Или вручную только объединить?

2018-03-19 05:37 UTC, merged